import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";

import "./globals.css";

import Navbar from "@/components/navbar/navbar";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} relative`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar className="fixed top-0" />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
